---

- name: "Computer init"
  hosts: "127.0.0.1"
  connection: "local"
  roles:
    - "common"
    - "cockpit"
    - "web"
  vars:
    web_servers:
      - name: "myhost.example.com"
        certificate_file_path: "/etc/letsencrypt/live/myhost.example.com/fullchain.pem"
        certificate_key_path: "/etc/letsencrypt/live/myhost.example.com/privkey.pem"
        extras:
          - |-
            location /cockpit/ {
                proxy_pass http://127.0.0.1:9090/cockpit/;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $remote_addr;
                proxy_set_header X-Forwarded-Proto $scheme;

                # Required for web sockets to function
                proxy_http_version 1.1;
                proxy_buffering off;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
            }
