---

- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present
  become: true

- name: Install php
  ansible.builtin.dnf:
    name: php
    state: present
  become: true

- name: Start and enable nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true
  become: true

- name: Start and enable php-fpm
  ansible.builtin.systemd:
    name: php-fpm
    state: started
    enabled: true
  become: true

- name: Include certbot install tasks
  when: install_certbot
  ansible.builtin.include_tasks: install-certbot.yml
