---

- name: Install common packages
  ansible.builtin.apt:
    update_cache: true
    name:
      - bsdgames
      - git
      - git-review
      - ffmpeg
      - htop
      - jq
      - neofetch
      - lsb-release
      - pandoc
      - pass
      - policycoreutils-sandbox
      - pwgen
      - python3-docutils
      - python3-psutil
      - strace
      - tmux
      - vim
    state: present
  become: true

- name: Include Debian desktop tasks
  when: is_desktop
  ansible.builtin.include_tasks: debian-desktop.yml
