---

- name: "Copy desktop files"
  ansible.builtin.copy:
    src: "gnome-desktop-background.png"
    dest: "{{ ansible_env.HOME }}/gnome-desktop-background.png"

- name: "Configure switch-applications keyboard shortcut"
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-applications"
    value: "['<Super>Tab']"

- name: "Configure switch-applications-backward keyboard shortcut"
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-applications-backward"
    value: "['<Shift><Super>Tab']"

- name: "Configure switch-windows keyboard shortcut"
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-windows"
    value: "['<Alt>Tab']"

- name: "Configure switch-windows-backward keyboard shortcut"
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-windows-backward"
    value: "['<Shift><Alt>Tab']"

- name: "Configure desktop picture options"
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'wallpaper'"

- name: "Configure desktop picture uri"
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'{{ ansible_env.HOME }}/gnome-desktop-background.png'"

- name: "Configure desktop screensaver options"
  community.general.dconf:
    key: "/org/gnome/desktop/screensaver/picture-options"
    value: "'wallpaper'"

- name: "Configure desktop screensaver uri"
  community.general.dconf:
    key: "/org/gnome/desktop/screensaver/picture-uri"
    value: "'{{ ansible_env.HOME }}/gnome-desktop-background.png'"

- name: "Configure desktop calendar show weekdate"
  community.general.dconf:
    key: "/org/gnome/desktop/calendar/show-weekdate"
    value: "true"

- name: "Configure desktop interface clock show seconds"
  community.general.dconf:
    key: "/org/gnome/desktop/interface/clock-show-seconds"
    value: "true"

- name: "Configure desktop interface clock show weekday"
  community.general.dconf:
    key: "/org/gnome/desktop/interface/clock-show-weekday"
    value: "true"

- name: "Configure desktop wm preferences"
  community.general.dconf:
    key: "/org/gnome/desktop/wm/preferences/button-layout"
    value: "'appmenu:minimize,maximize,close'"

- name: "Configure touchpad natural scrolling"
  community.general.dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll"
    value: "false"

- name: "Configure touchpad tap to click"
  community.general.dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
    value: "true"

- name: "Configure touchpad two finger scrolling"
  community.general.dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled"
    value: "true"
