---

- name: Copy Microsoft VSCode RPM repo
  ansible.builtin.copy:
      src: files/vscode.repo
      dest: /etc/yum.repos.d/vscode.repo
  become: true

- name: Install desktop packages
  ansible.builtin.dnf:
    name:
      - audacity
      - code
      - gimp
      - gnome-extensions-app
      - gnome-tweaks
      - remmina-plugins-rdp
      - snapd
    state: present
  become: true

- name: Install rpmfusion desktop packages
  when: rpm_fusion
  ansible.builtin.dnf:
    name: vlc
    state: present
  become: true

- name: Install desktop snap packages
  community.general.snap:
    name: spotify
    state: present
  become: true

- name: Configure Gnome
  when: "'gnome-shell' in ansible_facts.packages"
  ansible.builtin.include_tasks: gnome.yml
